##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://upenndigitalscholarship.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /petrodelphia
# location of code, the full url to your github repository
source-code: https://github.com/upenndigitalscholarship/petrodelphia

##########
# SITE SETTINGS
#
# title of site appears in banner
title: America's First Petrochemical Corridor
# tagline, a short phrase that will appear throughout the site in the top banner
tagline:
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This website provides you—and others who care about the past and future of Philadelphia—a rich collection of sources about the South Philadelphia refinery complex and other petrochemical facilities along the lower Schuylkill River. Fundamentally, this website is a research tool: a digital archive accompanied by reference works and maps. Stakeholders at various levels—neighborhood, municipal, Commonwealth, business, non-profit—should find information of interest among the articles, primary sources, data sheets, and “grey literature” (such as government documents and corporate reports) curated here. Whether you’re a student, teacher, planner, designer, developer, activist, journalist, or simply an infrastructure geek, you are invited to use this website to learn, to share, and to tell stories about fossil fuel legacies in South and Southwest Philadelphia."
footer: "An educational website about the history of the South Philadelphia refinery complex and the changing landscapes of the lower Schuylkill River."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords:
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Jared Farmer + Penn Libraries RDDS

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: 2025-09-23_Petro-Metadata
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'petro-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Research Data and Digital Scholarship (RDDS) at Penn Libraries"
organization-link: https://www.library.upenn.edu/rdds
# organization-logo-banner: 
organization-logo-nav: /assets/img/RDDS_Logo_Digital.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed

